services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ctf-lab-web
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.3

  ftp:
    build:
      context: .
      dockerfile: Dockerfile.ftp
    container_name: ctf-lab-ftp
    ports:
      - "21:21"
      - "20:20"
      - "21000-21010:21000-21010"
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.4

  ssh:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    container_name: ctf-lab-ssh
    ports:
      - "48884:22"
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.2
        
  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: ctf-lab-kali
    ports:
      - "22222:22"
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./kali_data:/home/jason/data

networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24 