services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: ctf-lab-web
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.2

  ftp:
    build:
      context: .
      dockerfile: ftp.Dockerfile
    container_name: ctf-lab-ftp
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.2

  ssh:
    build:
      context: .
      dockerfile: ssh.Dockerfile
    container_name: ctf-lab-ssh
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.2

  kali:
    build:
      context: .
      dockerfile: kali.Dockerfile
    container_name: ctf-lab-kali
    ports:
      - "1337:22"
    restart: unless-stopped
    networks:
      ctf-network:
        ipv4_address: 172.20.0.3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./kali_data:/home/jason/data

networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24